#!/bin/bash
clear
press_enter()
{
    echo -en "\nPress Enter to continue"
    read
    clear
}

restart()
{
	sudo reboot
}


echo This will remove all gphoto2 related packages and configurations
echo ""
press_enter
sudo apt purge gphoto2 ffmpeg vlc v4l2loopback-utils v4l2loopback-dkms mencoder
sudo apt autoremove
sudo cat /etc/modules-orig > /etc/modules
sudo rm /etc/modules-orig
sudo rm /etc/modprobe.d/dslr-webcam.conf
clear
echo Uninstall complete. System restart required.conf
press_enter
restart